# permissions for end users to view todolists.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: todolist-viewer-role
rules:
- apiGroups:
  - application.workshop.com
  resources:
  - todolists
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - application.workshop.com
  resources:
  - todolists/status
  verbs:
  - get
